[project]
name = "swfv"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2"
]

[project.scripts]
swfv = "swfv:cli.main"

[tool.setuptools.package-data]
'swfv' = ['themes/**']